# Generated by Django 3.1.4 on 2020-12-31 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='baseCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('name', models.CharField(max_length=1024)),
                ('course_code', models.CharField(max_length=20)),
                ('pre', models.CharField(max_length=1024)),
                ('anti', models.CharField(max_length=1024)),
                ('con', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='baseCourseCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('course_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NodeType', models.CharField(choices=[('NODE', 'One Course'), ('AND', 'And'), ('OR', 'OR'), ('OF', 'n OF a,b,c')], default='NODE', max_length=20)),
                ('MainCourse', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.basecourse')),
                ('child', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.node')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='MainCourse',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='courses.node'),
        ),
        migrations.AddField(
            model_name='course',
            name='Owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Course', to='courses.person'),
        ),
        migrations.AddField(
            model_name='basecourse',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.basecoursecode'),
        ),
    ]
