# Generated by Django 3.1.4 on 2020-12-27 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aCourse', models.CharField(choices=[('ACWR', 'ACWR Academic Writing'), ('ACCT', 'ACCT Accounting'), ('ACSC', 'ACSC Actuarial Science'), ('ENAE', 'ENAE Aerospace Engineering'), ('AFST', 'AFST African Studies'), ('ASL', 'ASL American Sign Language'), ('ANTH', 'ANTH Anthropology'), ('ALMC', 'ALMC Arabic Language and Muslim Cultures'), ('ARKY', 'ARKY Archaeology'), ('ARST', 'ARST Architectural Studies'), ('ARCH', 'ARCH Architecture'), ('APLA', 'APLA Architecture, Planning and Landscape'), ('ART', 'ART Art'), ('ARHI', 'ARHI Art History'), ('ARTS', 'ARTS Arts'), ('ASHA', 'ASHA Arts and Science Honours Academy'), ('ASTR', 'ASTR Astronomy'), ('ASPH', 'ASPH Astrophysics'), ('BCEM', 'BCEM Biochemistry'), ('BIOL', 'BIOL Biology'), ('BMEN', 'BMEN Biomedical Engineering'), ('BIST', 'BIST Biostatistics'), ('BOTA', 'BOTA Botany'), ('BSEN', 'BSEN Business and Environment'), ('BTMA', 'BTMA Business Technology Management'), ('CNST', 'CNST Canadian Studies'), ('CMMB', 'CMMB Cellular, Molecular and Microbial Biology'), ('CEST', 'CEST Central and East European Studies'), ('ENCH', 'ENCH Chemical Engineering'), ('CHEM', 'CHEM Chemistry'), ('CHIN', 'CHIN Chinese'), ('ENCI', 'ENCI Civil Engineering'), ('CMCL', 'CMCL Communication and Culture'), ('COMS', 'COMS Communication and Media Studies'), ('MDCH', 'MDCH Community Health Sciences'), ('CORE', 'CORE Community Rehabilitation'), ('CMDA', 'CMDA Computational Media Design'), ('ENCM', 'ENCM Computer Engineering'), ('CPSC', 'CPSC Computer Science'), ('COOP', 'COOP Co-operative Education'), ('DNCE', 'DNCE Dance'), ('DCED', 'DCED Dance Education'), ('DATA', 'DATA Data Science'), ('DEST', 'DEST Development Studies'), ('DRAM', 'DRAM Drama'), ('EASC', 'EASC Earth Science'), ('EALS', 'EALS East Asian Language Studies'), ('EAST', 'EAST East Asian Studies'), ('ECOL', 'ECOL Ecology'), ('ECON', 'ECON Economics'), ('EDUC', 'EDUC Education'), ('EDBT', 'EDBT Education Bridge to Teaching'), ('EDPS', 'EDPS Educational Psychology'), ('EDER', 'EDER Educational Research'), ('ENEL', 'ENEL Electrical Engineering'), ('ENEE', 'ENEE Energy and Environment, Engineering'), ('EESS', 'EESS Energy and Environmental Systems'), ('ENER', 'ENER Energy Engineering'), ('ENMG', 'ENMG Energy Management'), ('ENGG', 'ENGG Engineering'), ('ENGL', 'ENGL English'), ('ENTI', 'ENTI Entrepreneurship and Innovation'), ('EVDS', 'EVDS Environmental Design'), ('ENEN', 'ENEN Environmental Engineering'), ('ENSC', 'ENSC Environmental Science'), ('FILM', 'FILM Film'), ('FNCE', 'FNCE Finance'), ('FINA', 'FINA Fine Arts'), ('FREN', 'FREN French'), ('GEOG', 'GEOG Geography'), ('GLGY', 'GLGY Geology'), ('ENGO', 'ENGO Geomatics Engineering'), ('GOPH', 'GOPH Geophysics'), ('GERM', 'GERM German'), ('GREK', 'GREK Greek'), ('GRST', 'GRST Greek and Roman Studies'), ('HSOC', 'HSOC Health and Society'), ('HTST', 'HTST History'), ('INDL', 'INDL Indigenous Languages'), ('INDG', 'INDG Indigenous Studies'), ('ISEC', 'ISEC Information Security and Privacy'), ('INNO', 'INNO Innovation'), ('INTR', 'INTR International Relations'), ('INTE', 'INTE Internship'), ('IPHE', 'IPHE Interprofessional Health Education'), ('ITAL', 'ITAL Italian'), ('JPNS', 'JPNS Japanese'), ('KNES', 'KNES Kinesiology'), ('LAND', 'LAND Landscape Architecture'), ('LANG', 'LANG Language'), ('LLAC', 'LLAC Languages, Literatures and Cultures'), ('LATI', 'LATI Latin'), ('LAST', 'LAST Latin American Studies'), ('LAW', 'LAW Law'), ('LWSO', 'LWSO Law and Society'), ('LING', 'LING Linguistics'), ('MGST', 'MGST Management Studies'), ('ENMF', 'ENMF Manufacturing Engineering'), ('MRSC', 'MRSC Marine Science'), ('MKTG', 'MKTG Marketing'), ('MATH', 'MATH Mathematics'), ('ENME', 'ENME Mechanical Engineering'), ('MDGE', 'MDGE Medical Graduate Education'), ('MDPH', 'MDPH Medical Physics'), ('MDSC', 'MDSC Medical Science'), ('MDCN', 'MDCN Medicine'), ('MHST', 'MHST Museum and Heritage Studies'), ('MUSI', 'MUSI Music'), ('MUED', 'MUED Music Education'), ('MUPF', 'MUPF Music Performance'), ('NANS', 'NANS Nanoscience'), ('NEUR', 'NEUR Neuroscience'), ('NURS', 'NURS Nursing'), ('OPMA', 'OPMA Operations Management'), ('OBHR', 'OBHR Organizational Behaviour and Human Resources'), ('ENPE', 'ENPE Petroleum Engineering'), ('PHIL', 'PHIL Philosophy'), ('PHED', 'PHED Physical Education'), ('PHYS', 'PHYS Physics'), ('PLAN', 'PLAN Planning'), ('PLBI', 'PLBI Plant Biology'), ('POLI', 'POLI Political Science'), ('PLMA', 'PLMA Professional Land Management'), ('PSYC', 'PSYC Psychology'), ('PPOL', 'PPOL Public Policy'), ('REAL', 'REAL Real Estate Studies'), ('RELS', 'RELS Religious Studies'), ('RMIN', 'RMIN Risk Management and Insurance'), ('ROST', 'ROST Romance Studies'), ('RUSS', 'RUSS Russian'), ('SCPA', 'SCPA School of Creative and Performing Arts'), ('SCIE', 'SCIE Science'), ('SLAV', 'SLAV Slavic'), ('SOWK', 'SOWK Social Work'), ('SOCI', 'SOCI Sociology'), ('SENG', 'SENG Software Engineering'), ('ENSF', 'ENSF Software Engineering for Engineers'), ('SAST', 'SAST South Asian Studies'), ('SPPH', 'SPPH Space Physics'), ('SPAN', 'SPAN Spanish'), ('STAT', 'STAT Statistics'), ('STST', 'STST Strategic Studies'), ('SGMA', 'SGMA Strategy and Global Management'), ('SCMA', 'SCMA Supply Chain Management'), ('SUST', 'SUST Sustainability Studies'), ('SEDV', 'SEDV Sustainable Energy Development'), ('TAP', 'TAP Term Abroad Program'), ('TOUR', 'TOUR Tourism Management'), ('TRAN', 'TRAN Transportation Studies'), ('UNIV', 'UNIV University'), ('UNEX', 'UNEX University Exchange'), ('UBST', 'UBST Urban Studies'), ('VETM', 'VETM Veterinary Medicine'), ('WELL', 'WELL Wellbeing'), ('WMST', "WMST Women's Studies"), ('ZOOL', 'ZOOL Zoology')], max_length=20)),
                ('num', models.CharField(choices=[], max_length=5)),
                ('note', models.CharField(default='', max_length=200)),
                ('NodeType', models.CharField(choices=[('NODE', 'One Course'), ('AND', 'And'), ('OR', 'Or'), ('OF', 'n OF a,b,c')], default='NODE', max_length=20)),
                ('MainCourse', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course')),
                ('child', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.node')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='MainCourse',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='courses.node'),
        ),
        migrations.AddField(
            model_name='course',
            name='Owner',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.person'),
        ),
    ]
