# Generated by Django 3.1.4 on 2020-12-28 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='note',
            field=models.CharField(default='', max_length=200),
        ),
    ]
