# Generated by Django 3.1.4 on 2021-01-03 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210101_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.basecourse'),
        ),
        migrations.AlterField(
            model_name='node',
            name='child',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.node'),
        ),
    ]
