# Generated by Django 3.1.4 on 2020-12-28 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_node_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='child',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.node'),
        ),
    ]
