# Generated by Django 3.1.4 on 2021-01-04 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20210103_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='child',
            field=models.ManyToManyField(blank=True, null=True, to='courses.Node'),
        ),
    ]
