# Generated by Django 3.1.4 on 2020-12-28 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20201227_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='note',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
