# Generated by Django 3.1.4 on 2020-12-28 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20201227_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='num',
            field=models.IntegerField(),
        ),
    ]
