# Generated by Django 3.1.4 on 2020-12-28 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20201228_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='courses.person'),
        ),
    ]
