# Generated by Django 3.1.4 on 2020-12-28 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20201228_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='MainCourse',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AlterField(
            model_name='node',
            name='NodeType',
            field=models.CharField(choices=[('NODE', 'One Course'), ('AND', 'And'), ('OR', 'OR'), ('OF', 'n OF a,b,c')], default='NODE', max_length=20),
        ),
        migrations.AlterField(
            model_name='node',
            name='child',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.node'),
        ),
        migrations.AlterField(
            model_name='node',
            name='num',
            field=models.IntegerField(verbose_name=[(201, 201)]),
        ),
    ]
